"""One-off generator for app/teams_cfb.py — a static mapping from every name
variant The Odds API might use for an FBS team (school + mascot, plus known
aliases) to the canonical school name CFBD uses in historical games/lines
(e.g. "App State Mountaineers" -> "App State", matching CFBD's own school
field, which is itself an alias of "Appalachian State").

CFBD's /teams endpoint is the source of truth for school/mascot/alternateNames,
including cases where the two providers disagree in non-obvious ways (CFBD's
canonical "App State" vs. the fuller "Appalachian State", accented/curly-quote
names like "San José State" / "Hawai'i", etc.) — hand-typing this table risks
exactly those mismatches, so it's generated from live data instead. Re-run
this whenever team names drift (conference realignment, rebrands):

    python -m app.scripts.generate_cfb_teams
"""

import logging
import unicodedata

import httpx

from app.config import settings

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

OUTPUT_PATH = "app/teams_cfb.py"


def _variants(name: str) -> set[str]:
    """A name plus its accent-stripped and apostrophe-stripped forms, to
    absorb typographic differences between CFBD and The Odds API."""
    out = {name}
    ascii_name = unicodedata.normalize("NFKD", name).encode("ascii", "ignore").decode("ascii")
    out.add(ascii_name)
    for v in list(out):
        out.add(v.replace("’", "").replace("'", ""))
    return out


def build_mapping() -> dict[str, str]:
    if not settings.cfbd_api_key:
        raise RuntimeError("CFBD_API_KEY is not set — get a free key at https://collegefootballdata.com/key")

    client = httpx.Client(
        base_url="https://api.collegefootballdata.com",
        headers={"Authorization": f"Bearer {settings.cfbd_api_key}"},
        timeout=30.0,
    )
    resp = client.get("/teams", params={"classification": "fbs"})
    resp.raise_for_status()
    teams = [t for t in resp.json() if t.get("classification") == "fbs"]

    mapping: dict[str, str] = {}
    collisions = []
    for t in teams:
        school = t["school"]
        mascot = t.get("mascot")
        base_names = set(t.get("alternateNames") or []) | {school}

        all_names: set[str] = set()
        for n in base_names:
            all_names |= _variants(n)
        all_mascots = _variants(mascot) if mascot else {None}

        for name in all_names:
            for m in all_mascots:
                candidate = f"{name} {m}".strip() if m else name
                if candidate in mapping and mapping[candidate] != school:
                    collisions.append((candidate, mapping[candidate], school))
                mapping[candidate] = school

    if collisions:
        raise RuntimeError(f"Ambiguous team-name candidates, resolve manually: {collisions}")

    logger.info("Built %d name variants for %d FBS teams.", len(mapping), len(teams))
    return mapping


def write_module(mapping: dict[str, str]) -> None:
    lines = [
        '"""Maps every name variant The Odds API might use for an FBS team to',
        'the canonical school name CFBD uses in historical games/lines, so Elo',
        "ratings computed from history can be matched against live games.",
        "",
        "Generated by app/scripts/generate_cfb_teams.py — do not hand-edit.",
        '"""',
        "",
        "ODDS_API_CFB_NAME_TO_SCHOOL = {",
    ]
    for name in sorted(mapping):
        lines.append(f"    {name!r}: {mapping[name]!r},")
    lines.append("}")
    lines.append("")
    lines.append("")
    lines.append("def to_elo_key(team_name: str) -> str:")
    lines.append('    """Normalize a team name/abbreviation to the key used in the team_elo table."""')
    lines.append("    return ODDS_API_CFB_NAME_TO_SCHOOL.get(team_name, team_name)")
    lines.append("")

    with open(OUTPUT_PATH, "w") as f:
        f.write("\n".join(lines))
    logger.info("Wrote %s", OUTPUT_PATH)


if __name__ == "__main__":
    write_module(build_mapping())
